site_name: 'python-app'
site_description: 'Main documentation for python-app'
repo_url: https://github.com/kobibe/python-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started?: 'docs/index.md'
